# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push: 
    branches: ['main']
    paths-ignore:
      - "README.md"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout 
      uses: actions/checkout@v2

    - name: Remove unnecessary files
      run: |
        if [ -d opentab/devel ]; then
        rm -r opentab/devel;
        fi
        if [ -f Makefile ]; then
        rm Makefile;
        fi

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install jinja2-cli
        pip install opentab
        pip install pyyaml==5.4
        pip install jinja2-cli[yaml]

    - name: Take new version
      run: |
        VERSION=$(pip list | grep "opentab" | tr "opentab " " ")
        IFS="." read -r -a version_digits <<<"$VERSION"
        commit_message=$(git log --reverse -n 1 --pretty="%f")

        if [[ "$commit_message" == "Stable"* ]];
        then
            first_digit=${version_digits[0]}
            version_digits[1]=0
            version_digits[2]=0
            first_digit=$(expr $first_digit + "1")
            while [ $? -eq 2 ]
            do
                first_digit=$(expr $first_digit + "1")
            done
            version_digits[0]=$first_digit
        fi

        if [[ "$commit_message" == "Major"* ]];
        then
            second_digit=${version_digits[1]}
            version_digits[2]=0
            second_digit=$(expr $second_digit + "1")
            version_digits[1]=$second_digit
        fi

        if [[ "$commit_message" == "Minor"* ]];
        then
            third_digit=${version_digits[2]}
            third_digit=$(expr $third_digit + "1")
            version_digits[2]=$third_digit
        fi

        echo "VERSION=$(echo ${version_digits[*]} | tr " " ".")" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install jinja2-cli

    - name: Generate the setup.cfg with new version
      run: |
        echo 'version:' $VERSION >> version.yaml
        jinja2 setup.cfg.j2 version.yaml --format=yaml >> setup.cfg
        rm setup.cfg.j2 version.yaml

    - name: Build package
      run: python -m build

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
